enabled: true
production-mode: true
grid-size: grid-lg
header-fixed: true
header-animated: true
header-dark: false
header-transparent: false
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  'user/themes/quark/images/logo/Adobe Express - file.png':
    name: 'Adobe Express - file.png'
    full_path: 'Adobe Express - file.png'
    type: image/png
    size: 60850
    path: 'user/themes/quark/images/logo/Adobe Express - file.png'
custom_logo_mobile:
  'user/themes/quark/images/logo/Adobe Express - file.png':
    name: 'Adobe Express - file.png'
    full_path: 'Adobe Express - file.png'
    type: image/png
    size: 60850
    path: 'user/themes/quark/images/logo/Adobe Express - file.png'
